pipeline:
  build:
    image: ubuntu:16.04
    commands:
      - sleep 24
        #- ./ci/ping_mysql.sh
      - ./ci/install-deps.sh
      - ./ci/run_test.sh
  slack:
    image: plugins/slack
    channel: integration-test
    username: drone
    secrets: [ slack_webhook  ]
    when:
        status: [ success, failure  ]
services:
  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: zxcvbnm,./
      MYSQL_DATABASE: seafeventstest
